-- AlterTable
ALTER TABLE `Article` MODIFY `article_type` ENUM('STANDARD', 'FEDER', 'BUEGELHALTER', 'HALTEBUEGEL', 'ETUI', 'FLUEGEL', 'DESIGN', 'OEFFNER', 'VERPACKUNG', 'DRUCKERZEUGNIS', 'SONSTIGE') NULL DEFAULT 'STANDARD';
