-- AlterTable
ALTER TABLE `Contact` ADD COLUMN `gender` ENUM('MALE', 'FEMALE', 'DIVERSE') NULL DEFAULT 'MALE',
    ADD COLUMN `last_name` VARCHAR(191) NULL,
    ADD COLUMN `mail` VARCHAR(191) NULL,
    ADD COLUMN `phone_01` VARCHAR(191) NULL,
    ADD COLUMN `phone_02` VARCHAR(191) NULL,
    ADD COLUMN `pre_name` VARCHAR(191) NULL;
